improve scripts install default content

diff --git a/scripts/behat/drupal b/scripts/behat/drupal
--- a/scripts/behat/drupal
+++ b/scripts/behat/drupal
@@ -5,9 +5,29 @@ ps -ef | grep 'runserver' | grep -v grep | awk '{print $2}' | xargs kill -9
 
 scriptDir=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
 
-echo "Running Behat"
+SKIP_DEPEDENCIES=0
+SKIP_TESTS=0
 
-BEHAT_DATABASE=$1
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --skip-dependencies=*)
+      SKIP_DEPEDENCIES=1
+      ;;
+    --skip-tests=*)
+      SKIP_TESTS=1
+      ;;
+    --database=*)
+      BEHAT_DATABASE="${1#*=}"
+      ;;
+    *)
+      printf "\e[1;91m***************************\e[0m\n"
+      printf "\e[1;91m* Error: Invalid argument.*\e[0m\n"
+      printf "\e[1;91m***************************\e[0m\n"
+      exit 1
+  esac
+  shift
+done
+
 if [ ! -z "$MYSQL_USER" ]
 then
 # Codeship env.
@@ -20,17 +40,32 @@ elif [ ! -z "$BEHAT_DATABASE" ]
 then
   BEHAT_DATABASE="sqlite://localhost//tmp/development-qs.sqlite"
 fi
-echo "Database: $BEHAT_DATABASE"
 
 cd $scriptDir
 
 cd "../../"
 
-composer install
-bundle install
-bundle exec cap staging styleguide:build_local
+if [ $SKIP_DEPEDENCIES -eq 0 ]
+then
+  printf "\e[1;34m*************************\e[0m\n"
+  printf "\e[1;34m* Install dependencies. *\e[0m\n"
+  printf "\e[1;34m*************************\e[0m\n"
+
+  composer install
+  bundle install
+  bundle exec cap staging styleguide:build_local
+fi
 
 cd "web"
+
+printf "\e[1;35m******************************************\e[0m\n"
+printf "\e[1;35m* Install Drupal - Quariters Solidaires. *\e[0m\n"
+printf "\e[1;35m******************************************\e[0m\n"
+
+if [ ! -z "$BEHAT_DATABASE" ]
+then
+  printf "\e[1;93mthe database is: $BEHAT_DATABASE\e[0m\n"
+fi
 
 ../vendor/bin/drush si standard --db-url=$BEHAT_DATABASE --site-name='Behat' --account-name=admin --account-pass=admin --account-mail=behat@antistatique.net -y
 ../vendor/bin/drush ev '\Drupal::entityManager()->getStorage("shortcut_set")->load("default")->delete();'
@@ -39,15 +74,28 @@ cd "web"
 ../vendor/bin/drush en qs_default_content -y
 ../vendor/bin/drush updatedb -y
 ../vendor/bin/drush pmu hal serialization default_content qs_default_content -y
-nohup bash -c "php ../vendor/bin/drush runserver &" && sleep 3;
+
+if [ $SKIP_TESTS -eq 0 ]
+then
+  nohup bash -c "php ../vendor/bin/drush runserver &" && sleep 3;
+fi
 
 cd ".."
 
-set -e
-BEHAT_PARAMS='{"gherkin" : {"cache" : null}}' ./vendor/bin/behat --colors --strict
-behat_exit=$?
+if [ $SKIP_TESTS -eq 0 ]
+then
+  printf "\e[1;33m************************\e[0m\n"
+  printf "\e[1;33m* Running Behat Tests. *\e[0m\n"
+  printf "\e[1;33m************************\e[0m\n"
+exit
 
-# Kill runserver if one is alive
-ps -ef | grep 'runserver' | grep -v grep | awk '{print $2}' | xargs kill -9
+  set -e
+  BEHAT_PARAMS='{"gherkin" : {"cache" : null}}' ./vendor/bin/behat --colors --strict
+  behat_exit=$?
 
-exit $behat_exit
+  # Kill runserver if one is alive
+  ps -ef | grep 'runserver' | grep -v grep | awk '{print $2}' | xargs kill -9
+
+  exit $behat_exit
+fi
+
